### ISSUE TITLE
can't compile on local

### ISSUE THREAD

**Issue by chenshao0594** [inspire-software/yes-cart#40] opened 2017-11-29 07:35 UTC
sad
   can't compile on local with js error.

**Comment by iazarny** [comment] 2017-11-29 08:02
Hi could you provide the error message ? 
Thanks, Igor

**Comment by khangaikhuu** [comment] 2017-12-01 01:39
i'm getting this error when i compile for the first time.
[?[90m09:01:35?[39m] ?[31mFailed to load external module?[39m ?[35mts-node/register?[39m
[?[90m09:01:35?[39m] ?[31mFailed to load external module?[39m ?[35mtypescript-node/register?[39m
[?[90m09:01:35?[39m] ?[31mFailed to load external module?[39m ?[35mtypescript-register?[39m
[?[90m09:01:35?[39m] ?[31mFailed to load external module?[39m ?[35mtypescript-require?[39m
[?[90m09:01:35?[39m] ?[31mLocal gulp not found in?[39m ?[35m~\Desktop\shop\yes-cart\manager\jam-jsclient\src\main\typescript?[39m
[?[90m09:01:35?[39m] ?[31mTry running: npm install gulp?[39m

**Comment by iazarny** [comment] 2017-12-01 07:02
Hi 
It might be something wrong with node installation, so 
1. Local gulp not found, just - "Try running: npm install gulp".
2. navigate to "yes-cart/manager/jam-jsclient/src/main/typescript" and run "npm run build.dev"
   - this creates a build in dist/dev
3. navigate to "yes-cart/manager/jam" and run "mvn install"
   - this builds the jam war
   - it also includes "jam-jsclient/src/main/typescript/node_modules" and "jam-jsclient/src/main/typescript/dist/dev"

Fo rmore details look at manager\jam-jsclient\README.md

**Comment by inspire-software** [comment] 2017-12-01 15:34
This sounds like the same as #42 

Please try older nodejs/npm , the build could be failing due to typescript incompatibility.

Regards,
YC team

**Comment by khangaikhuu** [comment] 2017-12-04 02:16
i have tried with older version of nodejs/npm. 
nodejs = v5.12.0
npm = 3.10.10
i'm getting such error.
Can you help me to compile on local?
[?[90m07:23:49?[39m] Error on fetch for tslib.js at file:///C:/..../yes-cart-master/manager/jam-jsclient/src/main/typescript/node_modules/tslib.js
        Loading @angular/common/http
        Loading dist\tmp\app\app.module.js
        Loading dist\tmp\app\main.js
        Error: ENOENT: no such file or directory, open 'C:\.....\yes-cart-master\manager\jam-jsclient\src\main\typescript\node_modules\tslib.js'
    at Error (native)

**Comment by iazarny** [comment] 2017-12-04 08:18
Hi
Looks like windows issue wth npm https://github.com/npm/npm/issues/17444 
Other possible options to solve:

1. Just try workaround described here "Turns out my issue was our company's firewall and only c: drive was affected. Keeping my projects on another drive fixed the issue."
2. Use vargant

**Comment by inspire-software** [comment] 2017-12-04 08:49
Hi,

Just to add a bit of context to option #3. If you installed using another npm then node_modules will still have the dependencies loaded by that version of node, so you need to delete this directory completely to re-install dependencies (or force run).

Generally to be sure you have a completely clean build of jsclient you need to:
1. Delete node_modules directory (dependencies)
2. Delete dist directory (temp builds)
3. npm install (to install all dependencies)
4. npm run build.dev (or build.prod)

YC maven build cycle runs step #3 in clean phase and step #4 during process-resources. We do not run run steps #1 & #2 because these are expensive operations and take long time, and you only do them once (or when you have upgrades from core code)

Hope this helps,
YC team

**Comment by khangaikhuu** [comment] 2017-12-04 15:04
Hi,
It compiles without problem on MacOS with nodejs = 7.8.0, npm = 3.10.10.
it does not compile only on windows. i think it's permission or node problem on windows.

Thank you for your help.

**Comment by inspire-software** [comment] 2017-12-04 19:30
Hi @khangaikhuu,

We were able to reproduce your problem on a Windows machine. Seems like tslib needs path mapping in prod configuration of the build as well to make it work for Win.

[?[90m07:23:49?[39m] Error on fetch for tslib.js at file:///C:/..../yes-cart-master/manager/jam-jsclient/src/main/typescript/node_modules/tslib.js
Please update and try to re-build.

Ref: https://github.com/inspire-software/yes-cart/commit/7119764873e48d8a91e6e6dfc1c35d8901c6fd5a

Regards,
YC team

**Comment by inspire-software** [comment] 2017-12-11 18:53
Closing this issue as the situation seems to be resolved by latest changes.

**Closed by inspire-software** 2017-12-11 18:53 UTC
